### ISSUE TITLE
OAS Adapt to rulebook

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#15]
## Adaptation
Make the OAS fit the rules described in the `documentation/rules.md`
#### Rules
- You are allowed (it would even be nice) to give the option to expand beyond the rules
- The API needs to offer everything present in the rulebook
#### Tasks
- [x] Game Flow Actions
    - [x] Choosing robots
    - [x] Game start event
    - [x] ~(rulebook incomplete @kdanzer-tgm ) Timer events/fetching~
- [x] Energy cube status per Robot
- [x] Accessing current active robot and player & (optional) active register & their priority in general
- [x] Shop fill & dispose event
- [x] Accessing robot sub information (health/viable hand cards ezc)
- [x] Programming timer events
- [x] Register wipe event
- [x] Virtual Mode of robots
- [x] Checkpoints are entitys
- [x] Accessing Robot level (attitude) same as flying status
- [x] one way walls
- [x] add missing map parts

**Comment by ghost** [comment]
## Tiles

**Level**
Tiles should have an attribute named level which defines on which level the tile is. Possible values therefore should be -1, 0 and 1

**Special Tiles**
For every tile type should be an extra model. Otherwise there is a lot of information in the tile that is not relevant for all tile types.
