### ISSUE TITLE
[Task] Add consumers

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#19]
## Consumers

Right now only the clients who join the game have a `pat` (Player access token) and can therefore access the game

To be able to for example fetch events without having to join a game you should be able to register as a consumer to get a limited `pat`. Limited in terms of accessible Endpoints because many endpoints are not useful when you are  not a player.

#### Rules
- "fake" (consumer) `pat`s have to be useable same as "real" `pat`s
-  Restrict fake `pat`s with custom error messages
#### Tasks
- [x] Consumer backend
- [x] Consumer registration endpoints
- [x] Consumer `pat`s useable for certain actions
- [x] Restriction for non allowed actions

**Comment by nbrugger-tgm** [comment]
## Implemented

The functionality is implemented (`v0.4.0`)

## Testing

This feature is now in review by @jkolesik-tgm 

## Extension

Please post a list of all Endpoints that need to be accessible by consumers

**Format**   : `(API) : <method> <path>`
**Example** : (EventApi) : `GET /game/{game_id}/events/head`

Already done:

* (EventApi) : GET /game/{game_id}/events/head
* (EventApi) : GET /game/{game_id}/events/type

**Comment by jkolesik-tgm** [comment]
## Extension:
- (PlayersAPI): GET /game/{game_id}/players
- (PlayersAPI): GET /game/{game_id}/players/{player_id}

**Comment by nbrugger-tgm** [comment]
Implented in `v1.2.0`

**Comment by jkolesik-tgm** [comment]
## Extension:
- (RobotsAPI): GET /games/{game_id}/entitys/robots

**Comment by nbrugger-tgm** [comment]
- (RobotsAPI): GET /games/{game_id}/entities/robots/{robot_id}/registers/{register}
- (RobotsAPI): GET /games/{game_id}/entities/robots/{robot_id}/registers
- (RobotsAPI): GET /games/{game_id}/entities/robots/{robot_id}/info

**Comment by nbrugger-tgm** [comment]
Implemented `v1.3.0`
