### ISSUE TITLE
[Task] Physic System

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#21]
## Physic System
Physic implementation is needed. Meaning if a robot moves it pushes other robots and such stuff. 
#### Rules
- All Map tiles should affect the movement in a regarding way
- All Physical interactions from the core game should be implemented
- Should be extensible
- Interaction triggered by the map (eg. conveyor belt movment) shall not be included
#### Tasks
- [x] Walls block movement
- [x] Robots push each other
- [x] Lazers shooting
    - [x] Lazers can hit
    - [x] Lasers don't pass robots 
- [x] Falling of the map
- [ ] Make Puddle reduce movement
- [x] Different height levels
    - [x] Ramps
    - [x] Block on diff
    - [x] Fall one lvl down
- [ ] Trigger fields
    - [ ] Checkpoints
    - [ ] Energy points
    - [ ] Buttons  
- [x] Chain reactions (eg 1 push 2 and 2 pushes 3)
