### ISSUE TITLE
[Task] Create DEB installer

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#22]
## Create DEB installer

An installer for Linux is needed. Due to Ubuntu and Debian being very popular, DEB should be used as installer format

#### Rules
- Fully tested and executable under Debian and Ubuntu
- The installer should follow standards of the UNIX systems such as location of files
- After the installation the server should be startable with `service robo-rally start`
#### Tasks
- [ ] Create an installer
- [ ] Register/Enable Service (systemd)
- [x] Ensure dependenciemanagement
- [ ] Test
    - [x] WSL
    - [x] Ubuntu 20.04 (LTS)
    - [ ] Debian 9.x (LTS)
    - [ ] Docker Debian 9 (LTS)
    - [ ] Docker Ubuntu 20.04 (LTS)

**Comment by nbrugger-tgm** [comment]
### Progress
A single executable file can now be built
