### ISSUE TITLE
[Task] Config file

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#23]
## Configuration File
The Configuration file mentioned in the `README.md` should be read and applied by the server. As this is not needed when the server is started by an client there should be an `indipendent-mode`. In this mode the config file is ignored
#### Rules
- Includes all configs from the README
- Additional settings are added to the README table
#### Tasks
- [ ] Implement Serialization/Deserialisation
- [ ] Implement effect/apllying of the setting file (implementing functionality)
- [ ] Add `indipendent mode` as CLI/Programm start parameter
