### ISSUE TITLE
[Task] Documentation Upgrades & Programming cards

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#5]
## Documentation Upgrades & Programming cards
A documentation about all upgrade and programming cards is needed.
<br> Example
```markdown
### Penetrating shot
#### Description
Shooting a robot adds {add} additional virus cards 
**Price :** 3
| Parameter | From | To |
|------------|--------|---|
|      add     |     1    |  3 |
```
#### Rules
- Use English
- Write in markdown
- folder `/game-controller/documentation/`
- Use the format of the example
#### Tasks
- [ ] List of upgrade cards
- [ ] List parameters and ranges
- [x] List of programming cards
- [ ] "Special" Programming cards List
