### ISSUE TITLE
OAS Replace event system

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#6]
## Event system
Every client should have the possibility to access all happenings in the game based on a priority.<br>
~~Any action the API is doing should be known by the clients, but as not every client has the capability and need to know every animation, Events are split into 3 types.~~
~~- Necessary~~
~~- Recommended~~
~~- Nice to have~~

~~Add the possibility to fetch this information separately to the OAS~~
#### Rules
- Every player can get each event once
- Keep up the REST and FS design 
- Possible wait (lazy) fetch
#### Tasks
- [x] Define Event type class/entity
- [x] Define paths
- [x] Define a few Events
- [x] Remove old `/update` paths

**Comment by nbrugger-tgm** [comment]
### Realization
After some trouble in concept the solution I and @kdanzer-tgm found was to implement the updates in a kind of stack/query. It will implement the 'first in - first out' behavior.
#### Reason
This system is highly needed for animations and making the clients stay up to date. This kind of problem normally solved by letting the server inform the clients, this is not possible with APIs as it does not fit into the *request-response* schema.

Also by solving it with a query we can be very close to our  defined "File System like API" rules

**Comment by nbrugger-tgm** [comment]
### Change in assignment

> Any action the API is doing should be known by the clients, but as not every client has the capability and need to know every animation, Events are split into 3 types.
> 
> * Necessary
> * Recommended
> * Nice to have
>   Add the possibility to fetch this information separately to the OAS

In this regard this is not needed anymore as there are no 'nice to have' or in any way unnecessary updates/events

**Comment by nbrugger-tgm** [comment]
### Information pending
Waiting for https://github.com/FactoryRally/game-controller/issues/11

**Comment by nbrugger-tgm** [comment]
## Evolving System
The list of events is far away from a final stage but will be completed over time when we notice the missing entries

For now all documented Events are built into the OAS

**Comment by ghost** [comment]
## Missing paths

Not all event types do have a own path. They should get added.

**Comment by nbrugger-tgm** [comment]
## Completed

**Comment by nbrugger-tgm** [comment]
## Rework

With progress in development the number of events drastically increased. The idea of typesave event endpoints is not sustainable and makes not too much sense.

**Comment by nbrugger-tgm** [comment]
### Missing

The `DiscardUpgradesEvent` is missing

#### Attributes

* `robot_id`
* `discarded` : A list of the upgrades that got discarded

#### Tasks

* [x] Added to OAS
* [x] Implemented in Code

**Comment by nbrugger-tgm** [comment]
### Missing

The `MAP_CREATED` enum value in `EventType` is missing

- [x] OAS
- [x] Implementation

**Comment by nbrugger-tgm** [comment]
### Rewording

The class `GamePhaseChangedEvent` is used wrong.

While the event occurs when the GamePhase changes it **also** triggers when the game state changes. The State and the Phase are very different things and there should be a separate event. Also the `GamePhaseChangedEvent` doesn't has any information about the Phase but he state so this will change too

- [ ] ~Add the `GameStateChangedEvent`~
- [ ] ~Replace wrong usage of `GamePhaseChangedEvent` with the `GameStateChangedEvent`~
- [x] Change the `GamePhaseChangedEvent` to carry phases not states
- [x] OAS changed accordingly

**Comment by nbrugger-tgm** [comment]
### Update

> * Add the `GameStateChangedEvent`

This makes no sense since every important StateChange has it's own event type (eg. `PauseEvent`)

**Comment by nbrugger-tgm** [comment]
### Implemented
All changes implemented since `v1.4.0`

**Comment by nbrugger-tgm** [comment]
## Semi Complete
While not all events that will occur are covered, the system itself is completely refactored and the new structure shall be the final one.
Therefore this issue will be **closed**.

> Missing or new  demanded events should be discussed in one or more new issues
